my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <your_account>
      user: <your_user>
      password: <your_password>
      role: <role>
      database: <database>
      warehouse: <warehouse>
      schema: <schema>
